version: '3'

services:
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    command: [sh, -c, "npx prisma generate && npm start"]

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    command: npm start

  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
